# Generated by Django 5.1.4 on 2025-01-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlePage', models.CharField(max_length=200, verbose_name='заголовок')),
                ('titleContent', models.CharField(max_length=200, verbose_name='заголовок темы')),
                ('contentPage', models.TextField(verbose_name='контент(html)')),
            ],
        ),
    ]
