# Generated by Django 5.1.4 on 2025-01-15 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPython', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок страницы')),
                ('content', models.TextField(verbose_name='контента')),
            ],
        ),
        migrations.CreateModel(
            name='tableStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название таблицы')),
                ('data', models.TextField(verbose_name='HTML')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/img', verbose_name='Изображение')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='mainPython.statistic', verbose_name='название статистики')),
            ],
        ),
    ]
