# Generated by Django 5.1.4 on 2025-01-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPython', '0002_statistic_tablestatistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
