# Generated by Django 5.1.4 on 2025-01-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPython', '0004_demand_statistic_table_demand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_demand',
            name='stat',
        ),
        migrations.DeleteModel(
            name='Demand_statistic',
        ),
        migrations.DeleteModel(
            name='Table_Demand',
        ),
    ]
