# Generated by Django 5.1.4 on 2025-01-16 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPython', '0007_geography_statistic_table_geography'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills_statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
            ],
        ),
        migrations.CreateModel(
            name='Table_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название таблицы')),
                ('data', models.TextField(verbose_name='HTML')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/img', verbose_name='Изображение')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='mainPython.skills_statistic', verbose_name='название статистики')),
            ],
        ),
    ]
